apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  REDIS_SENTINEL_HOSTS: {{ .Values.config.redisSentinelHosts | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otlpEndpoint | quote }}
  OTEL_SERVICE_NAME: "websocket-counter"
  LOG_LEVEL: "info"
