apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-extra-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"   # Grafana sidecar scans for this label
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
